apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@noreply.local
      messageTemplate: |-
        chore(images): update
        {{- range .Changed.Images }}
        - {{ .Old }} → {{ .New }}
        {{- end }}
    push:
      branch: main
  update:
    path: ./agro_calc
    strategy: Setters
