apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-pvc.yaml
  - postgres-svc.yaml
  - postgres-statefulset.yaml
  - adminer-deploy.yaml
  - adminer-svc.yaml
  - agro-calc-deploy.yaml
  - agro-calc-svc.yaml
  - imagerepo.yaml
  - imagepolicy.yaml
  - image-update-automation.yaml
